spring.application.name=SpringBootEurekaClientApplication16
server.port=8081
server.servlet.context-path=/SpringBootEurekaClientApplication16
eureka.instance.instance-id=SpringBootEurekaClientApplication16
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka